### ISSUE TITLE
Enabled Languages Issues & Solutions

### ISSUE THREAD

**Issue by ArchBlood** [humhub/humhub-modules-translation-manager#2] opened 2020-09-04 21:33 UTC
Part 1: If you choose any of the default languages you'll see at the top of the container the selected languages, this shouldn't be viewable or could be seen as a code leakage.

Part 2: When selected and saved instead of staying checked the boxes are reset to blank, instead should be still marked with a check which should fix part 1 of this issue.

### Examples
![Screenshot_1](https://user-images.githubusercontent.com/35392110/92286099-0e61f680-eed4-11ea-97f8-c0621b9fc606.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/92286100-0efa8d00-eed4-11ea-981b-708dce2aef34.png)

**Comment by yurabakhtin** [comment] 2020-10-14 08:05
@luke- Part 1: I cannot reproduce this on current version, I think it was already fixed here https://git.humhub.org/professional/translation-manager/-/commit/29e5b4fff0e9750c9683cf3377c051e2116d0932#f96ab1acd65221b3224ec298c1882c4801bf13f3_16_13
Part 2: MR https://git.humhub.org/professional/translation-manager/-/merge_requests/2

**Comment by luke-** [comment] 2020-10-14 11:07
Fixed in 1.0.2 Release

**Closed by luke-** 2020-10-14 11:07 UTC
Labels: bug
